cmake_minimum_required(VERSION 3.15.0)

project(cobravmec LANGUAGES C CXX Fortran)

option(BUILD_PYTHON "Build Python wrapper" OFF)

set(CMAKE_VERBOSE_MAKEFILE ON CACHE BOOL "ON")

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")

if (SKBUILD)
  # Conda LDFLAGS already inject an rpath; avoid duplicate LC_RPATH entries.
  set(CMAKE_SKIP_RPATH TRUE)
endif ()

set(USER_INC_DIR "" CACHE FILEPATH "Set paths to include folders")
set(USER_LIB_DIR "" CACHE FILEPATH "Set paths to link folders")
include_directories(${USER_INC_DIR})
link_directories(${USER_LIB_DIR})

if (DEFINED ENV{CONDA_BUILD})
  link_directories("$ENV{BUILD_PREFIX}/lib")
  include_directories("$ENV{BUILD_PREFIX}/include")
  message(STATUS "Prefix environment variable is $ENV{BUILD_PREFIX}")
endif ()

get_filename_component(compiler ${CMAKE_Fortran_COMPILER} NAME)
if (${compiler} STREQUAL mpiifort OR ${compiler} STREQUAL mpifort OR ${compiler} STREQUAL ftn)
  add_definitions(-DMPI_OPT)
else ()
  find_package(MPI)
endif ()

if (MPI_Fortran_FOUND)
  add_definitions(-DMPI_OPT)
  set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} ${MPI_Fortran_COMPILE_FLAGS}")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${MPI_Fortran_LINK_FLAGS}")
  include_directories(${MPI_Fortran_INCLUDE_PATH})
endif ()

set(EXECUTABLE_OUTPUT_PATH ${CMAKE_CURRENT_BINARY_DIR}/build/bin)
set(LIBRARY_OUTPUT_PATH ${CMAKE_CURRENT_BINARY_DIR}/build/lib)

set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -cpp")
if (CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
  if (CMAKE_Fortran_COMPILER_VERSION VERSION_GREATER "10.0")
    set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fallow-argument-mismatch")
  endif()
endif()
set(CMAKE_Fortran_MODULE_DIRECTORY ${CMAKE_BINARY_DIR}/build/modules)

if (APPLE)
  add_definitions(-DMACOSX)
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -framework Accelerate")
endif ()
if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  add_definitions(-DLINUX)
endif()

set(NETCDF_INC_PATH "" CACHE PATH "Path to netcdf include directory")
set(NETCDF_LIB_PATH "" CACHE PATH "Path to netcdf library directory")

message(STATUS "NETCDF_INC_PATH is ${NETCDF_INC_PATH}")
if (NETCDF_INC_PATH)
  file(TO_NATIVE_PATH ${NETCDF_INC_PATH} NETCDF_INC_PATH)
  find_file(NETCDF_I netcdf.inc ${NETCDF_INC_PATH} NO_DEFAULT_PATH)
else ()
  get_directory_property(INC_DIRS INCLUDE_DIRECTORIES)
  find_file(NETCDF_I netcdf.inc ${INC_DIRS} NO_DEFAULT_PATH)
endif ()

if (NETCDF_LIB_PATH)
  file(TO_NATIVE_PATH ${NETCDF_LIB_PATH} NETCDF_LIB_PATH)
  find_library(NETCDF_F NAMES netcdff HINTS ${NETCDF_LIB_PATH} ENV LD_LIBRARY_PATH)
  find_library(NETCDF_C NAMES netcdf HINTS ${NETCDF_LIB_PATH} ENV LD_LIBRARY_PATH)
else()
  get_directory_property(LINK_DIRS LINK_DIRECTORIES)
  find_library(NETCDF_F NAMES netcdff HINTS ${LINK_DIRS} ENV LD_LIBRARY_PATH)
  find_library(NETCDF_C NAMES netcdf HINTS ${LINK_DIRS} ENV LD_LIBRARY_PATH)
endif ()

if (NETCDF_I AND (NETCDF_F OR NETCDF_C))
  message(STATUS "Using netcdf")
  add_definitions(-DNETCDF)
  include_directories(${NETCDF_INC_PATH})
  if (NETCDF_F)
    list(APPEND NETCDF_LIBRARIES ${NETCDF_F})
  endif ()
  if (NETCDF_C)
    list(APPEND NETCDF_LIBRARIES ${NETCDF_C})
  endif ()
else ()
  message(FATAL_ERROR "Failed to find required netcdf libraries. Set NETCDF_INC_PATH and NETCDF_LIB_PATH.")
endif ()

set(libstell_mini_sources "")
add_subdirectory(LIBSTELL_mini)

add_library(libstell_mini STATIC ${libstell_mini_sources})
if (SKBUILD)
  set_target_properties(libstell_mini PROPERTIES POSITION_INDEPENDENT_CODE ON)
endif()
set_target_properties(libstell_mini PROPERTIES Fortran_MODULE_DIRECTORY ${CMAKE_Fortran_MODULE_DIRECTORY}/libstell_mini)
target_include_directories(libstell_mini PUBLIC ${CMAKE_Fortran_MODULE_DIRECTORY}/libstell_mini)
target_link_libraries(libstell_mini PUBLIC ${NETCDF_LIBRARIES})
if (MPI_Fortran_FOUND)
  target_link_libraries(libstell_mini PUBLIC ${MPI_Fortran_LIBRARIES})
endif ()

add_subdirectory(COBRAVMEC)

if (SKBUILD OR BUILD_PYTHON)
  add_subdirectory(python)
endif ()
